// 第一章 Boss 两场台词（纸龙 B-5.x、铜雀 B-4.x），出自 studio/specs/dialogue-ch1-sky.md；船数按当前护送配置调整。
import type { Line } from './dialogue1';
export const BOSS_LINES:Line[]=[
 {id:"CH1.B03.01",trigger:"B-5.1-聚形完成",speaker:"屿长",emotion:'alarmed',text:"哎哟，你们快看那些纸！满天的纸片竹条都往一块儿飞，这、这是要干什么呀？",memory:false,pause:true},
 {id:"CH1.B03.02",trigger:"B-5.1-聚形完成",speaker:"麻杆",emotion:'smug',text:"帮主，网让他们拆了。护云梭的那只红鸟，屁股后头拉的墨烟写的是朱雀。",memory:false,pause:true},
 {id:"CH1.B03.03",trigger:"B-5.1-聚形完成",speaker:"雷公",emotion:'calm',text:"朱雀？那个镖局还没倒啊。一架穷云梭，也犯得着我把龙放出去……行，放吧，让我瞧瞧朱雀如今是个什么成色。",memory:false,pause:true,identity:"风筝帮帮主"},
 {id:"CH1.B03.04",trigger:"B-5.1-聚形完成",speaker:"二愣",emotion:'smug',text:"杆哥，帮主答应啦！放线，放线！",memory:false,pause:true},
 {id:"CH1.B03.05",trigger:"B-5.1-聚形完成",speaker:"小满",emotion:'alarmed',text:"纸龙？谁家风筝扎得这么大呀……屿长，让云梭靠拢些，千万别离远了！",memory:false,pause:true},
 {id:"CH1.B03.06",trigger:"B-5.1-聚形完成",speaker:"屿长",emotion:'alarmed',text:"靠拢，靠拢！王婶，把孩子都抱进舱里去！",memory:false,pause:true},
 {id:"CH1.BARK.B.01",trigger:"B-5.2-第一次贴签",speaker:"小满",emotion:"alarmed",text:"什么东西贴我尾巴上了？算盘，你看得清吗？",memory:false,pause:false},
 {id:"CH1.BARK.B.02",trigger:"B-5.2-第一次贴签",speaker:"算盘",emotion:"calm",text:"是张纸条，墨写的字，我认不全，像是在记什么。",memory:false,pause:false},
 {id:"CH1.BARK.B.03",trigger:"B-5.2-P1 HP≤20%",speaker:"二愣",emotion:"alarmed",text:"杆哥，龙头都瘪下去了！这龙不经打啊！",memory:false,pause:false},
 {id:"CH1.BARK.B.04",trigger:"B-5.2-P1 HP≤20%",speaker:"麻杆",emotion:"alarmed",text:"闭嘴！线放稳了，帮主在后头看着呢！",memory:false,pause:false},
 {id:"CH1.BARK.B.05",trigger:"B-5.3-第 1 道墙之后",speaker:"麻杆",emotion:"smug",text:"追！线放长点，别让那只红鸟溜了！",memory:false,pause:false},
 {id:"CH1.BARK.B.06",trigger:"B-5.3-第 1 道墙之后",speaker:"二愣",emotion:"alarmed",text:"杆哥，线快不够了，我手都勒出血啦！",memory:false,pause:false},
 {id:"CH1.BARK.B.07",trigger:"B-5.4-第一次扣船",speaker:"屿长",emotion:"alarmed",text:"哎哟！云梭往后拽啦！小满，别让它把我们拖走！",memory:false,pause:false},
 {id:"CH1.BARK.B.08",trigger:"B-5.4-夹被拆",speaker:"麻杆",emotion:"alarmed",text:"龙爪！我的龙爪！帮主的板子要落我身上了！",memory:false,pause:false},
 {id:"CH1.BARK.B.09",trigger:"B-5.5-纸甲落尽",speaker:"二愣",emotion:"alarmed",text:"杆哥，龙身上的纸全没啦！这、这可咋办？",memory:false,pause:false},
 {id:"CH1.BARK.B.10",trigger:"B-5.5-纸甲落尽",speaker:"麻杆",emotion:"alarmed",text:"慌什么！帮主，龙的皮烧了，您再给点法子！",memory:false,pause:false},
 {id:"CH1.BARK.B.11",trigger:"B-5.5-纸甲落尽",speaker:"雷公",emotion:"calm",text:"线别断。龙要是掉了，你们几个也跟着掉。",memory:false,pause:false},
 {id:"CH1.BARK.B.12",trigger:"B-5.6-「朱雀　待修」一行出现",speaker:"小满",emotion:"alarmed",text:"那上头写的是朱雀！它把咱们的字号写上去了！",memory:false,pause:false},
 {id:"CH1.BARK.B.13",trigger:"B-5.6-自我登记",speaker:"麻杆",emotion:"smug",text:"写上了就跑不掉！帮主的单子，从来没漏过一个！",memory:false,pause:false},
 {id:"CH1.BARK.B.14",trigger:"B-5.6-自我登记",speaker:"赤燕",emotion:"smug",text:"朱雀两个字，也是你们配写的？",memory:false,pause:false},
 {id:"CH1.B05.01",trigger:"B-5.7-封成功 2s 后",speaker:"二愣",emotion:'alarmed',text:"杆哥！线断啦，龙往下掉啦！",memory:false,pause:true},
 {id:"CH1.B05.02",trigger:"B-5.7-封成功 2s 后",speaker:"麻杆",emotion:'alarmed',text:"撤，都撤！……帮主，龙没了，您看这……",memory:false,pause:true},
 {id:"CH1.B05.03",trigger:"B-5.7-封成功 2s 后",speaker:"雷公",emotion:'calm',text:"没了就没了，纸扎的东西。前头就是铜雀关，一架穷云梭交不起过路钱，过不去的。都回来吧。",memory:false,pause:true},
 {id:"CH1.B05.04",trigger:"B-5.7-封成功 2s 后",speaker:"屿长",emotion:'alarmed',text:"哎哟，跑了，总算是跑了。算盘，云梭还在吧？你快给我看看。",memory:false,pause:true},
 {id:"CH1.B05.05",trigger:"B-5.7-封成功 2s 后",speaker:"算盘",emotion:'calm',text:"云梭还在。机身划破了一道口子，不进风，还能飞。",memory:false,pause:true},
 {id:"CH1.B05.06",trigger:"B-5.7-封成功 2s 后",speaker:"小满",emotion:'alarmed',text:"刚才那个人说什么过路钱？总镖头，前头还有关卡吗？",memory:false,pause:true},
 {id:"CH1.B05.07",trigger:"B-5.7-封成功 2s 后",speaker:"总镖头",emotion:'calm',text:"有，铜雀关。……到了再说。",memory:false,pause:true},
 {id:"CH1.B05.08",trigger:"B-5.7-封成功 2s 后",speaker:"赤燕",emotion:'calm',text:"到了再说？你们一架云梭，凑得出一份过路钱吗？",memory:false,pause:true},
 {id:"CH1.B05.09",trigger:"B-5.7-封成功 2s 后",speaker:"总镖头",emotion:'calm',text:"凑不出。凑不出也得过。",memory:false,pause:true},
 {id:"CH1.B07.01",trigger:"B-4.1-铜雀展翼挡口",speaker:"铜雀",emotion:'calm',text:"来的云梭听着：过铜雀关，一架云梭交三两雷石。交了，闸就开；交不出，请掉头回去。",memory:false,pause:true,identity:"守关机"},
 {id:"CH1.B07.02",trigger:"B-4.1-铜雀展翼挡口",speaker:"屿长",emotion:'alarmed',text:"三两？哎哟，一架云梭的炉子里统共也就这么点雷石，交出去我们拿什么飞啊！铜大爷，您行行好，云梭上都是老的老、小的小……",memory:false,pause:true},
 {id:"CH1.B07.03",trigger:"B-4.1-铜雀展翼挡口",speaker:"铜雀",emotion:'calm',text:"交不出，请掉头回去。",memory:false,pause:true},
 {id:"CH1.B07.04",trigger:"B-4.1-铜雀展翼挡口",speaker:"小满",emotion:'alarmed',text:"它就会这一句嘛！总镖头，掉头绕路的话，青石屿撑得到吗？",memory:false,pause:true},
 {id:"CH1.B07.05",trigger:"B-4.1-铜雀展翼挡口",speaker:"算盘",emotion:'calm',text:"撑不到。绕一圈要多飞好些天，屿上的雷石等不了那么久。",memory:false,pause:true},
 {id:"CH1.B07.06",trigger:"B-4.1-铜雀展翼挡口",speaker:"赤燕",emotion:'calm',text:"那就闯。小满，我在你右边。",memory:false,pause:true},
 {id:"CH1.B07.07",trigger:"B-4.1-铜雀展翼挡口",speaker:"总镖头",emotion:'calm',text:"咳……三十年前我带云梭过这儿，交的是实打实的雷石。今天交不起，只好对不住它了。臭丫头，闯过去，让云梭贴着你走。",memory:false,pause:true},
 {id:"CH1.B07.08",trigger:"B-4.1-铜雀展翼挡口",speaker:"小满",emotion:'smug',text:"好嘞！屿长，让云梭贴紧我，谁也别落单！",memory:false,pause:true},
 {id:"CH1.B07.09",trigger:"B-4.1-铜雀展翼挡口",speaker:"铜雀",emotion:'alarmed',text:"拒不交钱，按闯关处置。",memory:false,pause:true},
 {id:"CH1.B07.10",trigger:"B-4.1-铜雀展翼挡口",speaker:"屿长",emotion:'alarmed',text:"都抓紧了！孩子抱好，锅碗瓢盆都捆上！",memory:false,pause:true},
 {id:"CH1.B08.02",trigger:"B-4.2-玩家首次中弹",speaker:"总镖头",emotion:'alarmed',text:"咳，挨一下就挨一下，别愣着，云梭还在你后头呢。",memory:false,pause:false},
 {id:"CH1.B08.04",trigger:"B-4.2-破招成功",speaker:"小满",emotion:'smug',text:"哈，从光边上翻过去啦！",memory:false,pause:false},
 {id:"CH1.B08.06",trigger:"B-4.2-破招失败",speaker:"算盘",emotion:'calm',text:"光柱擦到朱雀了，机身焦了一块，这个得记账。",memory:false,pause:false},
 {id:"CH1.B08.07",trigger:"B-4.2-T1 HP≤20%",speaker:"赤燕",emotion:'calm',text:"它胸口的铜在发红，快撑不住了！",memory:false,pause:false},
 {id:"CH1.B08.08",trigger:"B-4.2-转场",speaker:"小满",emotion:'alarmed',text:"翅膀上的锁亮起来啦！",memory:false,pause:false},
 {id:"CH1.B08.10",trigger:"B-4.3-第一侧破招成功",speaker:"小满",emotion:'smug',text:"穿过去啦！锁开了一边！",memory:false,pause:false},
 {id:"CH1.B08.12",trigger:"B-4.3-外甲落下",speaker:"算盘",emotion:'calm',text:"掉下来一块铜甲，没砸到云梭，记一笔。",memory:false,pause:false},
 {id:"CH1.B08.13",trigger:"B-4.3-第二侧外甲落下",speaker:"小满",emotion:'smug',text:"两边都松啦，翅膀上的炮哑了一半！",memory:false,pause:false},
 {id:"CH1.B08.15",trigger:"B-4.3-玩家中弹",speaker:"算盘",emotion:'calm',text:"朱雀中弹，这笔修理费我先垫着。",memory:false,pause:false},
 {id:"CH1.B08.16",trigger:"B-4.3-T2 HP≤20%",speaker:"屿长",emotion:'alarmed',text:"铜鸟的翅膀都垂下来啦！小满，加把劲啊！",memory:false,pause:false},
 {id:"CH1.B08.17",trigger:"B-4.3-转场",speaker:"铜雀",emotion:'calm',text:"翼炮失效。改用脚部。",memory:false,pause:false},
 {id:"CH1.B08.36",trigger:"B-4.6-协助分支",speaker:"赤燕",emotion:'smug',text:"说好不替你收尾的，这回算我手滑。让开！",memory:false,pause:false},
 {id:"CH1.B08.37",trigger:"B-4.6-封成功",speaker:"小满",emotion:'smug',text:"圈住啦！铜鸟，别动了！",memory:false,pause:false},
 {id:"CH1.B08.38",trigger:"B-4.6-封成功",speaker:"铜雀",emotion:'calm',text:"控制器已封。关闸程序，终止。",memory:false,pause:false},
];
export const BOSS_DIALOGUE_BY_ID:Record<string,Line>=Object.fromEntries(BOSS_LINES.map(l=>[l.id,l]));
