// 第二章台词（2026-10-03 按 docs/story.md 重写）。气泡键名是代码里的敌机种类，显示名见 CH2_NAME。
import type { Line } from './dialogue1';
export const CH2_LINES:Line[]=[
 {id:"C2.S01.01",trigger:"C2.P1.riverNight",speaker:"小满",emotion:'alarmed',text:"这就是蜃海啊……雾好大，前面什么都看不清。",memory:false,pause:true,identity:"朱雀镖局的镖师"},
 {id:"C2.S01.02",trigger:"C2.P1.riverNight",speaker:"赤燕",emotion:'calm',text:"雾里一排一排的灯，就是蜃吐出来的假灯吧？看着还挺好看的。",memory:false,pause:true,identity:"小满的师姐"},
 {id:"C2.S01.03",trigger:"C2.P1.riverNight",speaker:"老盾",emotion:'calm',text:"越好看越不能跟。小满，咱们先往前探探路，让云梭在后头慢慢跟上来。",memory:false,pause:true,identity:"老镖师"},
 {id:"C2.S01.04",trigger:"C2.P1.riverNight",speaker:"小满",emotion:'smug',text:"好！大家只跟着朱雀的尾灯走，别的灯一盏都别看！",memory:false,pause:true},
 {id:"CH2.BARK.S.05",trigger:"C2.s05",speaker:"小满",emotion:"alarmed",text:"到处都是蜘蛛网，缝窄得跟针眼似的！",memory:false,pause:false},
 {id:"CH2.BARK.S.06",trigger:"C2.s05",speaker:"赤燕",emotion:"smug",text:"怕什么，你钻得过去，我就跟着你钻。",memory:false,pause:false},
 {id:"CH2.BARK.S.03",trigger:"C2.s04",speaker:"老盾",emotion:"alarmed",text:"那艘帆船拿光照着云梭呢，快把它打下来！",memory:false,pause:false},
 {id:"C2.S04.01",trigger:"C2.P4.origin",speaker:"小满",emotion:'alarmed',text:"好险！刚才云梭差点跟着那几盏假灯拐走了。",memory:false,pause:true},
 {id:"C2.S04.02",trigger:"C2.P4.origin",speaker:"老盾",emotion:'calm',text:"云梭上的人说，那灯一亮，舵就自己往那边偏，拉都拉不回来。",memory:false,pause:true},
 {id:"C2.S04.03",trigger:"C2.P4.origin",speaker:"赤燕",emotion:'calm',text:"这么下去可不行。灯这么多，咱们也分不出哪盏是真的。",memory:false,pause:true},
 {id:"C2.S04.04",trigger:"C2.P4.origin",speaker:"老盾",emotion:'calm',text:"我听人说过，这片雾里住着一只机械鸟，叫墨鸢，靠采光过日子。真灯假灯，她一眼就认得。",memory:false,pause:true},
 {id:"C2.S04.05",trigger:"C2.P4.origin",speaker:"小满",emotion:'smug',text:"那咱们就去找她！盾叔，云梭就拜托您看紧了。",memory:false,pause:true},
 {id:"CH2.BARK.S.22",trigger:"C2.s07",speaker:"赤燕",emotion:"alarmed",text:"那门炮在瞄云梭！趁它还在蓄力，打断它！",memory:false,pause:false},
 {id:"C2.S07.01",trigger:"C2.P6.bellSilence",speaker:"赤燕",emotion:'calm',text:"小满，雾越来越浓了。云梭要是再被假灯拐一次，可就找不回来了。",memory:false,pause:true},
 {id:"C2.S07.02",trigger:"C2.P6.bellSilence",speaker:"赤燕",emotion:'calm',text:"这样吧，我去贴着云梭飞，给他们引路。你跟盾叔去前头找墨鸢。",memory:false,pause:true},
 {id:"C2.S07.03",trigger:"C2.P6.bellSilence",speaker:"小满",emotion:'alarmed',text:"师姐，那你一个人要小心啊！",memory:false,pause:true},
 {id:"C2.S07.04",trigger:"C2.P6.bellSilence",speaker:"赤燕",emotion:'smug',text:"放心吧，有事我喊你。快去快回！",memory:false,pause:true},
 {id:"CH2.BARK.S.11",trigger:"C2.s17",speaker:"小满",emotion:"alarmed",text:"前面石崖上一闪一闪的……好像有只鸟被一群鱼追着！",memory:false,pause:false},
 {id:"C2.S08.01",trigger:"C2.moyuanJoin",speaker:"墨鸢",emotion:'alarmed',text:"救命啊！这群镜鱼追了我一路，要抢我罐子里的光！",memory:false,pause:true,identity:"在雾里采光的机械鸟"},
 {id:"C2.S08.02",trigger:"C2.moyuanJoin",speaker:"小满",emotion:'alarmed',text:"别怕，往我这边飞！盾叔，后头交给您了！",memory:false,pause:true},
 {id:"C2.S08.03",trigger:"C2.moyuanJoin",speaker:"老盾",emotion:'alarmed',text:"来吧！都躲到我盾后头！",memory:false,pause:true},
 {id:"C2.S08.04",trigger:"C2.moyuanIntro",speaker:"墨鸢",emotion:'calm',text:"呼……多谢你们。你们是从哪儿来的？这片雾里，很少有人敢飞进来。",memory:false,pause:true},
 {id:"C2.S08.05",trigger:"C2.moyuanIntro",speaker:"小满",emotion:'smug',text:"我们是朱雀镖局的，护着一艘云梭去天门。你就是墨鸢吧？听说真灯假灯你都认得？",memory:false,pause:true},
 {id:"C2.S08.06",trigger:"C2.moyuanIntro",speaker:"墨鸢",emotion:'calm',text:"认得。假灯是蜃吐出来的，看着亮，凑近了是凉的。真灯是人点的，暗一点，可是暖和。",memory:false,pause:true},
 {id:"C2.S08.07",trigger:"C2.moyuanIntro",speaker:"老盾",emotion:'calm',text:"姑娘，能不能给我们领个路？云梭上三百多口人，可不能在这儿迷了路。",memory:false,pause:true},
 {id:"C2.S08.08",trigger:"C2.moyuanIntro",speaker:"墨鸢",emotion:'smug',text:"三百多口人？那可不能让蜃吃了。行，我给你们带路，跟紧我！",memory:false,pause:true},
 {id:"CH2.BARK.S.13",trigger:"C2.s15",speaker:"小满",emotion:"alarmed",text:"那些打伞的看着跟真人似的……打了没事吧？",memory:false,pause:false},
 {id:"CH2.BARK.S.14",trigger:"C2.s15",speaker:"墨鸢",emotion:"calm",text:"放心打，都是蜃变出来的，里头是空的。",memory:false,pause:false},
 {id:"CH2.BARK.S.23",trigger:"C2.s11",speaker:"小满",emotion:"smug",text:"墨鸢，你这一下可真厉害！",memory:false,pause:false},
 {id:"CH2.BARK.S.24",trigger:"C2.s11",speaker:"墨鸢",emotion:"smug",text:"嘿嘿，在雾里混了这么多年，总得会两手。",memory:false,pause:false},
 {id:"C2.S09.01",trigger:"C2.P8.belowCloud",speaker:"墨鸢",emotion:'calm',text:"往下看。这一排九盏灯，才是真灯。",memory:false,pause:true},
 {id:"C2.S09.02",trigger:"C2.P8.belowCloud",speaker:"小满",emotion:'calm',text:"这么暗啊……还没刚才那些假灯一半亮。",memory:false,pause:true},
 {id:"C2.S09.03",trigger:"C2.P8.belowCloud",speaker:"墨鸢",emotion:'calm',text:"真灯是人点的，当然没那么亮。顺着这九盏走，就能出蜃海。",memory:false,pause:true},
 {id:"C2.S09.04",trigger:"C2.P8.belowCloud",speaker:"老盾",emotion:'calm',text:"那还等什么，走到头不就出去了？",memory:false,pause:true},
 {id:"C2.S09.05",trigger:"C2.P8.belowCloud",speaker:"墨鸢",emotion:'alarmed',text:"没那么简单。出口那儿蹲着蜃，不把它打跑，谁也出不去。",memory:false,pause:true},
 {id:"C2.S09.06",trigger:"C2.P8.belowCloud",speaker:"小满",emotion:'smug',text:"那就把它打跑！",memory:false,pause:true},
 {id:"C2.S11.01",trigger:"C2.MR.arrival",speaker:"墨鸢",emotion:'calm',text:"到了，前面就是蜃。小满，你看那个大贝壳里的灯。",memory:false,pause:true},
 {id:"C2.S11.02",trigger:"C2.MR.arrival",speaker:"小满",emotion:'alarmed',text:"好多灯……跟一整座城似的！",memory:false,pause:true},
 {id:"C2.S11.03",trigger:"C2.MR.arrival",speaker:"蜃",emotion:'smug',text:"哎呀，客官们一路辛苦啦！快进港歇歇脚吧！热汤热饭，软床软被，小店一文钱都不收！",memory:false,pause:true,identity:"云海里的蜃"},
 {id:"C2.S11.04",trigger:"C2.MR.arrival",speaker:"小满",emotion:'alarmed',text:"又是假港口！骗了那么多船还不够，还想骗我们？",memory:false,pause:true},
 {id:"C2.S11.05",trigger:"C2.MR.arrival",speaker:"蜃",emotion:'smug',text:"客官怎么说话呢？进来看看嘛，看了保准就不想走了……",memory:false,pause:true},
 {id:"C2.S11.06",trigger:"C2.MR.arrival",speaker:"老盾",emotion:'calm',text:"别跟它废话。云梭停在后头，我守着。小满，打它！",memory:false,pause:true},
 {id:"C2.S11.07",trigger:"C2.MR.arrival",speaker:"小满",emotion:'smug',text:"好！墨鸢，帮我盯着哪个是它的真身！",memory:false,pause:true},
 {id:"C2.S11.08",trigger:"C2.MR.arrival",speaker:"墨鸢",emotion:'smug',text:"交给我！",memory:false,pause:true},
 {id:"CH2.BARK.S.15",trigger:"B-MR-07",speaker:"蜃",emotion:"alarmed",text:"哎哟哟，轻点轻点，小店的门面都让你们打花了！",memory:false,pause:false},
 {id:"CH2.BARK.S.17",trigger:"B-MR-09",speaker:"墨鸢",emotion:"calm",text:"闪紫光的那个是真的，别的都是假影子！",memory:false,pause:false},
 {id:"CH2.BARK.S.18",trigger:"B-MR-15",speaker:"蜃",emotion:"smug",text:"客官，往灯这边靠，这边稳当～",memory:false,pause:false},
 {id:"CH2.BARK.S.19",trigger:"B-MR-15",speaker:"老盾",emotion:"alarmed",text:"云梭被灯拽过去了！快把灯打灭！",memory:false,pause:false},
 {id:"CH2.BARK.S.25",trigger:"B-MR-21",speaker:"老盾",emotion:"alarmed",text:"壳要合上了！先打坏两边的壳铰！",memory:false,pause:false},
 {id:"CH2.BARK.S.20",trigger:"B-MR-26",speaker:"赤燕",emotion:"alarmed",text:"云梭被壳夹住了！小满，快想办法！",memory:false,pause:false},
 {id:"CH2.BARK.S.21",trigger:"B-MR-37",speaker:"墨鸢",emotion:"smug",text:"我来！放几盏假灯，看它上不上当！",memory:false,pause:false},
 {id:"C2.S13.01",trigger:"B-MR-18",speaker:"蜃",emotion:'alarmed',text:"哎呀呀，客官们下手这么狠，小店扛不住了！快，给雷公捎个信！",memory:false,pause:true},
 {id:"C2.S13.02",trigger:"B-MR-19",speaker:"小满",emotion:'alarmed',text:"它在叫人！那道光往右上边飞走了！",memory:false,pause:true},
 {id:"C2.S13.03",trigger:"B-MR-20",speaker:"老盾",emotion:'calm',text:"管它叫谁，先把眼前这个收拾了！",memory:false,pause:true},
 {id:"C2.S13.04",trigger:"B-MR-27",speaker:"蜃",emotion:'calm',text:"灯……都灭了……这儿本来就是一片空云，哪有什么港口……",memory:false,pause:true},
 {id:"C2.S13.05",trigger:"B-MR-28",speaker:"蜃",emotion:'calm',text:"雷公会来的……你们走不远的……",memory:false,pause:true},
 {id:"C2.S13.06",trigger:"B-MR-29",speaker:"墨鸢",emotion:'calm',text:"假的就是假的，灯一灭，什么都不剩。",memory:false,pause:true},
 {id:"C2.S14.01",trigger:"C2.MR.reveal",speaker:"小满",emotion:'calm',text:"总算把它打跑了！大家都没事吧？",memory:false,pause:true},
 {id:"C2.S14.02",trigger:"C2.MR.reveal",speaker:"墨鸢",emotion:'calm',text:"它不知道吞了多少条船。你看壳里，堆的全是那些船上的雷石。",memory:false,pause:true},
 {id:"C2.S14.03",trigger:"C2.MR.reveal",speaker:"老盾",emotion:'smug',text:"正好，云梭的雷石也快烧完了。搬几块添上，够咱们飞出蜃海了。",memory:false,pause:true},
 {id:"C2.S14.04",trigger:"C2.MR.reveal",speaker:"墨鸢",emotion:'calm',text:"壳里还剩一团蜃气。小满，你收着，往后用它变几个假影子，敌人就分不清哪个是你了。",memory:false,pause:true},
 {id:"C2.S14.05",trigger:"C2.MR.reveal",speaker:"小满",emotion:'smug',text:"好东西！谢啦，墨鸢！",memory:false,pause:true},
 {id:"C2.S15.01",trigger:"C2.end.thunderCall",speaker:"赤燕",emotion:'alarmed',text:"小满，右上边那片云里有艘大船……是雷公！",memory:false,pause:true},
 {id:"C2.S15.02",trigger:"C2.end.thunderCall",speaker:"雷公",emotion:'smug',text:"蜃让你们拆了？又是朱雀镖局。好啊，前面就是雷场，天上的雷石都在我手里。想过去，先问问我的雷答不答应！",memory:false,pause:true,identity:"风筝帮帮主"},
 {id:"C2.S15.03",trigger:"C2.end.thunderCall",speaker:"小满",emotion:'alarmed',text:"不管你有多少雷，我们都要过去！你等着！",memory:false,pause:true},
 {id:"C2.S15.04",trigger:"C2.end.thunderCall",speaker:"老盾",emotion:'calm',text:"大家先找个地方歇一宿，养足了精神，明天闯雷场。",memory:false,pause:true},
];
export const CH2_BUBBLES={
 灯笼:{'01':"进来坐坐嘛，不要钱！",'02':"灯灭了……还没骗到人……"},
 税蟹:{'01':"过路费！不交就横着走！",'02':"钳子断了，钱还没收呢！"},
 帆船:{'01':"跟我走，保证不迷路！",'02':"迷路的是我……"},
 旋翼:{'01':"加急快递！请签收炮弹！",'02':"差评别给我……"},
 灯船:{'01':"看我多亮！快来追我！",'02':"亮不动了……"},
 纸鳐:{'01':"请柬送到！你被我盯上啦！",'02':"请柬……湿了……"},
 潮梭:{'01':"港口马上就到，真的！",'02':"骗……骗不动了……"},
 网蛛:{'01':"床给你织好了，躺下别起来！",'02':"我的床……没织完……"},
 镜鱼:{'01':"镜子里的你最帅，来看看！",'02':"镜子碎了，七年倒霉……"},
 铃鳗:{'01':"当——开饭啦！",'02':"钟哑了，我下班……"},
 蛾:{'01':"灯！好多灯！我要抱住！",'02':"我的灯……"},
 伞客:{'01':"没下雨，我就是爱撑伞！",'02':"伞……我的伞……"},
};
export const CH2_NAME:Record<keyof typeof CH2_BUBBLES,string>={灯笼:"假笑灯笼",税蟹:"收费蟹",帆船:"领路帆",旋翼:"快递旋翼",灯船:"晃眼灯船",纸鳐:"请柬鳐",潮梭:"画饼梭",网蛛:"铺床蛛",镜鱼:"自恋镜鱼",铃鳗:"破钟鳗",蛾:"扑灯蛾",伞客:"撑伞怪"};
export const CH2_BRIEFS=[
 ['任务一　探路','蜃海里的假灯','在雾里给云梭探出一条路'],
 ['任务二　护送云梭','青石屿的云梭','打灭假航灯，拆掉对着云梭的炮'],
 ['任务三　穿过蜃海','蜃','拆壳阀、圈真影、灭假灯、断壳铰'],
] as const;
