// 操作、玩家阵位技能与秘技的无头验收；六格游戏截图仅写 skills.png。
// node tools/validate-p6-19.mjs <dev URL> <证据目录>
import puppeteer from 'puppeteer-core';
import assert from 'node:assert/strict';
import {mkdirSync,mkdtempSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
const base=process.argv[2]??'http://127.0.0.1:5193/',out=resolve(process.argv[3]??'studio/jobs/P6-19'),tmp=mkdtempSync(tmpdir()+'/p6-19-');mkdirSync(out,{recursive:true});
const report={checks:[],values:{},errors:[]};
const browser=await puppeteer.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--use-angle=vulkan','--enable-features=Vulkan','--ignore-gpu-blocklist','--autoplay-policy=no-user-gesture-required']});
try{
 const page=await browser.newPage();await page.setViewport({width:1600,height:900});page.on('pageerror',e=>report.errors.push(e.message));
 await page.evaluateOnNewDocument(()=>{window.requestAnimationFrame=()=>0;});await page.goto(base,{waitUntil:'load'});await page.waitForFunction('window.__game',{timeout:60000,polling:100});
 const prep=()=>page.evaluate(()=>{const g=window.__game,w=g.world;g.testRun=null;g.debug.god=g.debug.bot=g.debug.autofire=false;w.setDifficulty('normal');w.newGame();w.resetStage();w.player.x=450;w.player.y=850;w.player.ink=1;w.player.invuln=0;w.skills.setUnlocked(['chaifa','tishen','zhongpao','shenying','bilei']);g.state='playing';g.ui.screen('none');g.r.setBackground('stage1');g.render();document.querySelector('.opening-controls').hidden=true;window.sample=(x,y,hp=10000)=>{const e=w.spawn({sprite:'e_swallow',hp,radius:22,noCollide:true,score:0},x,y);e.hp=e.maxHp=hp;e.info={...e.info,maskR:0};return e;};});
 const step=n=>page.evaluate(n=>{const g=window.__game;for(let i=0;i<n;i++){g.input.poll();g.update(1/60);}},n);
 const tap=async key=>{await page.keyboard.down(key);await step(1);await page.keyboard.up(key);await step(1);};
 const move=async(x,y)=>{const r=await page.evaluate(()=>window.__game.r.playCss);await page.mouse.move(r.x+x*r.w/900,r.y+y*r.h/1200);};
 const shot=async i=>{await page.evaluate(()=>window.__game.render());await new Promise(r=>setTimeout(r,100));await page.screenshot({path:`${tmp}/${i}.png`});};
 const sequence=async keys=>{for(const key of keys)await page.keyboard.press(key);};
 const allCode=['ArrowUp','ArrowUp','ArrowDown','ArrowDown','ArrowLeft','ArrowRight','ArrowLeft','ArrowRight','KeyB','KeyA','KeyB','KeyA'];
 const godCode=['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyA','KeyB','KeyA','KeyB'];
 // 同一条400px笔画的耗墨、减速与停火完全一致，包括同时按左键的空格组合。
 const modes=[];
 for(const mode of ['right','both','space']){await prep();await move(170,550);if(mode==='space')await page.keyboard.down('Space');else await page.mouse.down({button:'right'});if(mode!=='right')await page.mouse.down({button:'left'});await step(1);await move(570,550);await step(1);
  modes.push(await page.evaluate(()=>{const g=window.__game,w=g.world;return{ink:w.player.ink,active:w.brush.active,firing:w.player.firing,shots:w.player.shots.length,scale:w.timeScale};}));
  if(mode==='space')await page.keyboard.up('Space');else await page.mouse.up({button:'right'});if(mode!=='right')await page.mouse.up({button:'left'});await step(1);
 }
 assert.deepEqual(modes[0],modes[1]);assert.deepEqual(modes[0],modes[2]);assert.equal(modes[0].firing,false);assert.equal(modes[0].shots,0);assert.ok(modes[0].active);report.values.brush=modes;
 for(const first of ['left','right']){await prep();await move(200,500);const second=first==='left'?'right':'left';await page.mouse.down({button:first});await page.mouse.down({button:second});await step(1);assert.equal(await page.evaluate(()=>window.__game.world.player.firing),false);await page.mouse.up({button:first});await step(1);await page.mouse.up({button:second});await step(1);assert.equal(await page.evaluate(()=>window.__game.input.mouse.size),0);}
 await prep();await move(330,710);await shot(0);assert.equal(await page.$eval('.pen-cursor',e=>e.getBoundingClientRect().width),36);
 await tap('KeyF');assert.equal(await page.evaluate(()=>window.__game.world.bombsUsed),1);report.checks.push('三种执笔相同：停火、400px扣10%墨；F泼墨、36px光标');
 // 对话期间持空格不翻页；回到战斗一直屏蔽到释放后再次按下。
 await prep();await page.evaluate(()=>window.__game.ui.chapterSay({name:'小满'},'calm','验收对白一。验收对白二。','p6-input',false,{pause:true,onDone:()=>{},onSkip:()=>{}}));await page.keyboard.down('Space');await step(90);assert.ok(await page.evaluate(()=>window.__game.world.dialoguePaused));await tap('Enter');await step(4);assert.equal(await page.evaluate(()=>window.__game.world.brush.active),false);await page.keyboard.up('Space');await step(1);await move(150,500);await page.keyboard.down('Space');await step(1);assert.equal(await page.evaluate(()=>window.__game.world.brush.active),true);await page.keyboard.up('Space');await step(1);report.checks.push('对白持空格不翻页，退场释放后才能重新起笔');
 // 全部伙伴技能在鼠标离场时仍可施放；盾随玩家，截流绕玩家，俯冲优先Boss弱点，网选择最密前方。
 await prep();await page.evaluate(()=>{const w=window.__game.world;w.companions.setRoster(['laodun']);w.input.pointer.inside=false;assertCast();function assertCast(){if(!w.companions.cast('Q'))throw Error('护盾施放失败');}});await step(12);await shot(1);
 const shield=await page.evaluate(()=>{const w=window.__game.world;w.player.x+=70;w.companions.update(.1);const a=w.companions.areas[0];w.shoot(w.player.x+50,w.player.y,0,0);w.companions.update(.01);return{dx:a.x-w.player.x,dy:a.y-w.player.y,blocked:w.companions.stats.blocked};});assert.equal(shield.dx,0);assert.equal(shield.dy,0);assert.equal(shield.blocked,1);
 await prep();const partners=await page.evaluate(()=>{const w=window.__game.world;w.input.pointer.inside=false;w.companions.setRoster(['suanpan']);w.shoot(w.player.x,w.player.y,0,0);w.companions.cast('Q');const clear=w.bullets.list[0].dead;w.companions.setRoster(['chiyan']);const weak=sample(330,360);weak.data.bossOwner={def:{boss:{name:'样本'}}};weak.data.weakWeapon='red';sample(450,730);w.companions.cast('Q');const dive={x:w.companions.dash.x,y:w.companions.dash.y};w.companions.setRoster(['moyuan']);sample(280,400);sample(290,405);sample(650,650);w.companions.cast('Q');const net={x:w.companions.areas[0].x,y:w.companions.areas[0].y,fromX:w.companions.areas[0].fromX,fromY:w.companions.areas[0].fromY};w.companions.setRoster(['chiyan','laodun']);w.companions.charge=100;w.companions.cast('R');return{clear,dive,net,joint:{x:w.companions.joint.x,y:w.companions.joint.y}};});assert.equal(partners.clear,true);assert.deepEqual(partners.dive,{x:330,y:360});assert.ok(partners.net.x<400&&partners.net.y<500);assert.equal(partners.net.fromX,450);assert.deepEqual(partners.joint,{x:450,y:850});report.values.partners=partners;report.checks.push('四伙伴与R离开鼠标可用，护盾跟随、截流居中、Boss弱点、密集墨网');
 await prep();await page.evaluate(()=>{window.target=sample(450,500);});await tap('Digit2');await step(11);await shot(2);assert.equal(await page.evaluate(()=>window.__game.world.skills.decoys.length),3);
 const unfolded=await page.evaluate(()=>window.__game.world.skills.decoys.map(d=>({x:d.x,y:d.y})));assert.ok(unfolded[0].x<450&&unfolded[1].x>450&&unfolded[2].y<850);
 await page.evaluate(()=>{const w=window.__game.world,d=w.skills.decoys[0];for(let i=0;i<8;i++)w.shoot(d.x,d.y,0,0);w.skills.intercept();});assert.equal(await page.evaluate(()=>window.__game.world.skills.stats.decoyHits),8);assert.ok(await page.evaluate(()=>window.__game.world.skills.decoys[0].rushing));for(let i=0;i<120&&await page.evaluate(()=>window.target.hp===10000);i++)await step(1);await step(4);await shot(3);await step(90);assert.ok(await page.evaluate(()=>window.target.hp<10000));assert.equal(await page.evaluate(()=>window.__game.world.skills.decoys.length),0);report.checks.push('三纸替身展开、8次挡弹、优先被瞄准、主动撞敌造成伤害');
 await prep();await page.evaluate(()=>window.__game.world.player.weapon='blue');await page.mouse.down({button:'left'});await tap('Digit1');await step(20);await shot(4);assert.match(await page.$eval('.overclock-clock',e=>e.textContent),/超频/);assert.ok(await page.evaluate(()=>window.__game.world.skills.boosted));await page.mouse.up({button:'left'});await step(280);assert.equal(await page.evaluate(()=>window.__game.world.skills.boosted),false);report.checks.push('拆阀5秒、机身发红、粗弹与火尾、头顶倒计时、收阀白汽');
 // 重炮三个命中层级；聚光后900速度，三级顿帧后爆炸；伤害保留150/300/500。
 for(const [hits,level,damage] of [[40,1,150],[100,2,300],[180,3,500]]){await prep();await page.evaluate(hits=>{const w=window.__game.world;window.target=sample(450,500);for(let i=0;i<hits;i++)w.skills.primaryHit();},hits);assert.equal(await page.evaluate(()=>window.__game.world.skills.cannonLevel),level);await tap('Digit3');assert.equal(await page.evaluate(()=>window.__game.world.skills.cannons.length),0);await step(5);const cannon=await page.evaluate(()=>({y:window.__game.world.skills.cannons[0].y,real:window.__game.world.real}));await step(1);assert.ok(Math.abs(cannon.y-await page.evaluate(()=>window.__game.world.skills.cannons[0].y)-15)<1e-7);await step(50);assert.equal(await page.evaluate(()=>10000-window.target.hp),damage);}
 report.checks.push('重炮40/100/180命中蓄力、0.1s聚光、900速度、三级150/300/500伤害');
 await prep();await tap('Digit4');await step(17);assert.ok(await page.evaluate(()=>Math.abs(window.__game.world.skills.echo.x-window.__game.world.player.x)>=240));await page.evaluate(()=>{const w=window.__game.world,s=w.skills;window.target=sample(s.echo.x,500);for(let i=0;i<25;i++)w.shoot(s.echo.x,s.echo.y,0,0);s.intercept();});assert.equal(await page.evaluate(()=>window.__game.world.skills.pearls),20);await step(343);assert.equal(await page.evaluate(()=>window.__game.world.skills.mirrorLeft),0);await step(70);assert.equal(await page.evaluate(()=>10000-window.target.hp),400);report.checks.push('蜃影0.3s分离、至少240距离、吞弹上限20、结束20颗各20伤害');
 for(const perfect of [true,false]){await prep();await page.evaluate(()=>{window.targets=[sample(450,500),sample(540,520),sample(620,550)];});await tap('Digit5');if(!perfect)await step(10);await page.evaluate(()=>{const w=window.__game.world;w.shoot(w.player.x,w.player.y-80,Math.PI/2,300);});await step(1);assert.equal(await page.evaluate(()=>window.__game.world.skills.stats.reflected),1);assert.equal(await page.evaluate(()=>window.__game.world.skills.stats.perfect),perfect?1:0);if(perfect){assert.equal(await page.evaluate(()=>window.__game.world.hitstopRemaining),.06);assert.deepEqual(await page.evaluate(()=>window.targets.map(e=>10000-e.hp)),[30,30,30]);}else assert.ok(await page.evaluate(()=>{const w=window.__game.world,s=w.skills.returns[0];return Math.abs(Math.hypot(s.vx,s.vy)-900*w.diff.speed)<1e-8;}));}
 report.checks.push('避雷针0.15s完美雷击连锁3敌/顿帧60ms，之后按原方向反弹3倍速');
 // 真实章节入口和真实键序列，无效序列、过时拒绝、重复不能关闭、跨章保留、重开清除。
 await page.evaluate(async()=>{const g=window.__game;g.world.newGame();await g.startStage(0);g.world.root.cancel();g.world.player.y=850;});await sequence(allCode.slice(0,-1));assert.equal(await page.evaluate(()=>window.__game.world.allSkills),false);await page.keyboard.press('KeyA');await step(1);assert.equal(await page.evaluate(()=>window.__game.world.allSkills),true);assert.equal(await page.evaluate(()=>window.__game.world.skills.unlocked.size),5);await sequence(godCode);await step(1);assert.equal(await page.evaluate(()=>window.__game.world.cheatGod),true);await shot(5);
 await sequence(allCode);await sequence(godCode);assert.ok(await page.evaluate(()=>window.__game.world.allSkills&&window.__game.world.cheatGod));
 const cd=await page.evaluate(()=>{const w=window.__game.world;w.skills.use('chaifa');w.companions.setRoster(['laodun']);w.companions.cast('Q');w.player.ink=0;w.player.bombs=0;window.__game.applyDebug();return{skill:w.skills.cooldowns.chaifa,partner:w.companions.team[0].cooldown,ink:w.player.ink,bombs:w.player.bombs,colors:w.inkScore.levels};});assert.equal(cd.skill,5);assert.equal(cd.partner,3);assert.equal(cd.ink,1);assert.ok(cd.bombs>0);assert.deepEqual(cd.colors,{red:3,blue:3,purple:3});report.values.allSkills=cd;
 await page.evaluate(async()=>{const g=window.__game;await g.startStage(1);g.world.root.cancel();});assert.ok(await page.evaluate(()=>window.__game.world.allSkills&&window.__game.world.cheatGod));
 await page.evaluate(async()=>{const g=window.__game;g.world.newGame();await g.startStage(0);g.world.root.cancel();});assert.equal(await page.evaluate(()=>window.__game.world.allSkills||window.__game.world.cheatGod),false);
 await new Promise(r=>setTimeout(r,10100));await sequence(allCode);await sequence(godCode);assert.equal(await page.evaluate(()=>window.__game.world.allSkills||window.__game.world.cheatGod),false);
 await page.evaluate(async()=>{const g=window.__game,mod=await import('/src/game/test-options.ts');g.toTitle();g.onTestStart({...mod.defaultTestOptions(),allSkills:true});});await page.waitForFunction('window.__game.state==="playing"');assert.equal(await page.evaluate(()=>window.__game.world.allSkills),true);report.checks.push('两条秘技真实键入成功、不可取消、跨章保留、重开清掉、实际10秒后拒绝；测试菜单同效');
 assert.deepEqual(report.errors,[]);
 execFileSync('python3',['-c',`from PIL import Image,ImageDraw,ImageFont\nfrom pathlib import Path\nimport sys\nsrc,out=sys.argv[1:]\nlabels=['光标 · 双描边笔尖','老盾 · 护盾罩住玩家','替身 · 左右前展开','替身 · 撞敌炸开','拆阀 · 超频倒计时','秘技 · 解锁技能栏']\ncanvas=Image.new('RGB',(2400,976),'#151c20');d=ImageDraw.Draw(canvas);font=ImageFont.truetype('local-source/ZhuqueFangsong-Regular.ttf',24)\nfor i,label in enumerate(labels):\n x=(i%3)*800;y=(i//3)*488;im=Image.open(Path(src)/f'{i}.png').convert('RGB');im=im.resize((800,450));canvas.paste(im,(x,y+38));d.text((x+16,y+5),label,font=font,fill='#f3e6ca')\ncanvas.save(Path(out)/'skills.png')`,tmp,out]);
 writeFileSync(`${out}/validation.json`,JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser.close();}
